image: atlassian/default-image:latest

definitions:
  steps:
    - step: &run-tests
        script:
          - pip3 install -r requirements.txt
          - pip3 install -e .
          - pytest

pipelines:
  custom:
    validate-wrappers:
      - step: *run-tests
  tags:
    v*:
      - step: *run-tests
  branches:
    master:
      - step: *run-tests
