image: atlassian/default-image:latest

pipelines:
  custom:
    validate-wrappers:
      - step:
          script:
            - python ductus/tools/wrappers.py
  tags:
    v*:
      - step:
          script:
            - python ducutus/tools/wrappers.py
  branches:
    master:
      - step:
          script:
            - python ductus/tools/wrappers.py 
