image: python:3.5.1

pipelines:
  custom:
    validate-wrappers:
      - step:
          script:
            - python auctornotitia/tools/wrappers.py
  branches:
    master:
      - step:
          script:
            - python auctornotitia/tools/wrappers.py 
