image: atlassian/default-image:latest

pipelines:
  custom:
    validate-wrappers:
      - step:
          script:
            - python auctornotitia/tools/wrappers.py
  branches:
    master:
      - step:
          script:
            - python auctornotitia/tools/wrappers.py 
